# Generated by Django 5.2.7 on 2025-10-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_id',
            new_name='employee_id',
        ),
    ]
